apiVersion: v1
kind: Pod
metadata:
  name: frontend-demo-app
  labels:
   name: frontend-demo-app
   app: demo-voting-app
spec:
  containers:
  - name: frontend-demo
    image: kodekloud/examplevotingapp_vote:v1
    ports:
    - containerPort: 80