apiVersion: v1
kind: pod
metadata:
  name: frontend-demo-app
  labels:
   name: frontend-demo-app
   project: myproject
spec:
  containers:
  - name: frontend-demo
    image: kodekloud/examplevotingapp_vote:v1
    ports:
    - containerPort: 80