apiVersion: v1
kind: Service
metadata:
  name: forfrontend-demo
  labels:
    project: myproject
spec:
  selector:
    name: frontend-demo-app
    project: myproject
  type: NodePort  
  ports:
      - port: 80
        targetPort: 80
        nodePort: 30002