apiVersion: v1
kind: Pod
metadata:
  name: postgres-demo-app
  labels:
   name: postgres-demo-app
   project: myproject
spec:
  containers:
  - name: postgres-demo
    image: postgres:alpine
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_USER
      value: "postgres" 
    - name: POSTGRES_PASSWORD
      value: "postgres"
