apiVersion: v1
kind: Pod
metadataa:
  name: redis-demo-app
  labels:
   name: redis-demo-app
   project: myproject
spec:
  containers:
  - name: redis-demo
    image: redis:alpine
    ports:
    - containerPort: 6379
    