apiVersion: v1
kind: Pod
metadata:
  name: redis-demo-app
  labels:
   name: redis-demo-app
   app: demo-voting-app
spec:
  containers:
  - name: redis-demo
    image: redis:latest
    ports:
    - containerPort: 6379
