apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    project: myproject
spec:
  selector:
    name: redis-demo-app
    project: myproject
  ports:
      - port: 6379
        targetPort: 6379