apiVersion: v1
kind: Service
metadata:
  name: forresult-app
  labels:
    app: demo-voting-app
spec:
  selector:
    name: result-app
    app: demo-voting-app
  type: NodePort  
  ports:
      - port: 80
        targetPort: 80
        nodePort: 30003
        